gatsby-config.js
package.json
src/UI-Kit/Button/Button.tsx
src/UI-Kit/Footer/Footer.tsx
src/UI-Kit/Header/Header.tsx
src/UI-Kit/Link/Link.tsx
src/UI-Kit/Navbar/Navbar.tsx
src/UI-Kit/Tile/Tile.tsx
src/UI-Kit/index.tsx
src/layouts/index.tsx
src/pages/404.tsx
src/pages/about.tsx
src/pages/case-studies.tsx
src/pages/index.tsx
src/pages/projects.tsx
src/templates/caseStudyTemplate.tsx
src/templates/projectTemplate.tsx
src/utils/index.tsx
tsconfig.json
tslint.json
yarn.lock

This PR adds a TS Linter to the repo, plus it updates all of the files to not throw any lint errors.

Type Checking

---

src/UI-Kit/Footer/Footer.module.scss
src/UI-Kit/Footer/Footer.tsx
src/UI-Kit/Header/Header.module.scss
src/UI-Kit/Header/Header.tsx
src/pages/case-studies.tsx
src/templates/caseStudy.scss
src/templates/caseStudyTemplate.tsx

This PR:
- Adds a link to the footer brand
- Improves the layout of the Case Study page
- Adds a tagline to the Case Study

Case Study UI Improvements

---

gatsby-config.js
package.json
src/UI-Kit/Footer/Footer.tsx
src/UI-Kit/Navbar/Navbar.tsx
src/UI-Kit/PostTile/PostTile.module.scss
src/UI-Kit/PostTile/PostTile.tsx
src/UI-Kit/PostTile/index.tsx
src/UI-Kit/index.tsx
src/declarations.d.ts
src/pages/index.tsx
src/styles/global.scss
src/utils/routes.tsx
yarn.lock

This PR:
- Adds medium posts to the home page
- Adds a routes file and implements that across the site

Medium Posts

---

gatsby-config.js
package.json
src/layouts/index.tsx
src/pages/about.tsx
src/pages/case-studies.tsx
src/pages/index.tsx
src/pages/projects.tsx
src/templates/caseStudyTemplate.tsx
src/templates/projectTemplate.tsx
src/typings.d.ts
src/utils/Helmet.tsx
yarn.lock

This PR:
- Adds a sitemap
- Adds page description to metadata in head
- Refactors the page metadata to pass it through using an object

Better SEO

---

package.json
scripts/create-blog-post.js
yarn.lock

This PR:
- Adds a little cli script to make creating a new blog post super fast
Resolves https://github.com/thetrevorharmon/thetrevorharmon.com/issues/152
~- [ ] I have run `yarn build` locally to ensure that it builds correctly OR I have verified it builds with a deploy preview.~ N/A

🔧 `create-blog-post` script

---

plugins/gatsby-remark-mermaid-to-svg/gatsby-remark-mermaid-to-svg.mjs

This PR:
- Adds caching to mermaid remark plugin
No

✨ Add caching to mermaid remark plugin

---

src/content/blog/drafts/codemirror-and-react/Callout/Callout.tsx
src/content/blog/drafts/codemirror-and-react/Callout/index.ts
src/content/blog/drafts/codemirror-and-react/ReactCodeMirrorSyncStateExample/ReactCodeMirrorSyncStateExample.tsx
src/content/blog/drafts/codemirror-and-react/ReactCodeMirrorSyncStateExample/constants.ts
src/content/blog/drafts/codemirror-and-react/codemirror-and-react.mdx

This PR:
- Adds a conclusion to the `CodeMirror and React` article
- Adds a `<Callout />` component to that article
https://github.com/thetrevorharmon/thetrevorharmon.com/issues/151

📝 Added conclusion to CodeMirror and React article

---

src/components/CodeEditor/CodeEditor.scss
src/components/CodeEditor/CodeEditor.tsx
src/content/blog/drafts/learning-codemirror/FacetExample/FacetExample.tsx
src/content/blog/drafts/learning-codemirror/FacetExample/StateFieldExample.tsx
src/content/blog/drafts/learning-codemirror/FacetExample/index.ts
src/content/blog/drafts/learning-codemirror/StateFieldExample/StateFieldExample.tsx
src/content/blog/drafts/learning-codemirror/StateFieldExample/index.ts
src/content/blog/drafts/learning-codemirror/learning-codemirror.mdx
src/styles/Mermaid.scss
src/styles/syntaxHighlighting.scss
src/templates/Post.tsx
src/templates/Project.tsx
src/utils/helpers.tsx

This PR:
- Adds the initial draft for `Learning CodeMirror`
- Styles panels in CodeMirror
- Sets the theme correctly in the `<CodeEditor />` component
- Small fix for mermaid diagrams
No

📝 Learning CodeMirror

---

gatsby-config.ts
package.json
src/components/Link/Link.tsx
src/styles/global.scss
yarn.lock

This PR:
- Adds auto-linking of post headers
- Fixes a weird visual bug with links + trailing icons + underlines
Resolves https://github.com/thetrevorharmon/thetrevorharmon.com/issues/144

✨ Autolink post headers

---

src/components/Container/Container.tsx
src/components/FollowCallout/FollowCallout.tsx
src/components/Footer/Footer.tsx
src/components/Link/Link.tsx
src/components/ReadingList/ReadingList.tsx
src/content/blog/drafts/what-ive-been-up-to-lately/what-ive-been-up-to-lately.mdx
src/layouts/Layout.tsx
src/layouts/PostLayout.tsx
src/utils/routes.tsx

This PR:
- 📝 Updates 'What I've been up to lately'
- 🎨 New follow, reading list, and footer design
No

Update post, redesign post body

---

.vscode/settings.json
src/content/blog/drafts/learning-codemirror/StateFieldExample/StateFieldExample.tsx
src/content/blog/drafts/learning-codemirror/learning-codemirror.mdx

This PR:
- Worked more on the `Learning CodeMirror` article
No

📝 Learning CodeMirror (3rd draft)

---

src/content/blog/drafts/displaying-mermaid-charts-in-gatsby/displaying-mermaid-charts-in-gatsby.mdx

This PR:
- Makes small changes to `Displaying Mermaid charts in Gatsby`
No

📝 Tweaks to "Displaying Mermaid charts in Gatsby"

---

.vscode/settings.json
gatsby-config.mjs
package.json
src/content/blog/drafts/loaves-and-fishes/Citation/Citation.tsx
src/content/blog/drafts/loaves-and-fishes/Citation/index.ts
src/content/blog/drafts/loaves-and-fishes/loaves-and-fishes.mdx
src/content/pages/about/about.mdx
src/styles/global.scss
src/templates/Page.tsx
tsconfig.json
yarn.lock

This PR:
- Adds a draft for `Loaves and Fishes`
- Adds support for github flavored markdown
- Updates vscode settings to format documents on save
No

📝 Loaves and Fishes (draft)

---

src/content/blog/2023/displaying-mermaid-charts-in-gatsby/displaying-mermaid-charts-in-gatsby.mdx

This PR:
- Publishes the "Displaying Mermaid Charts in Gatsby" article
No

📝 Published "Displaying Mermaid charts in Gatsby"

---

src/components/FeaturedTile/FeaturedTile.tsx
src/content/blog/2024/connecting-antlr-to-codemirror-6-building-a-language-server/connecting-antlr-to-codemirror-6-building-a-language-server.mdx

This PR:
- Publishes "Building a Language Server"
No

📝 Publish "Building a Language Server"

---

package.json
src/components/Button/Button.tsx
src/components/CodeEditor/CodeEditor.scss
src/components/CodeEditor/CodeEditor.tsx
src/components/Icon/Icon.scss
src/components/Icon/Icon.tsx
src/components/Icon/icons/circle.svg
src/components/Icon/icons/email.svg
src/components/Icon/icons/index.tsx
src/components/Icon/icons/link.svg
src/components/Icon/icons/loading.svg
src/components/Icon/icons/play.svg
src/components/Icon/icons/rss.svg
src/components/Icon/icons/twitter.svg
src/components/Icon/icons/x.svg
src/components/Link/Link.tsx
src/components/Meta/Meta.tsx
src/content/blog/drafts/advanced-state-management-with-react-and-codemirror/CodeEditor/CodeEditor.tsx
src/content/blog/drafts/advanced-state-management-with-react-and-codemirror/CodeEditor/components/StatusBar.tsx
src/content/blog/drafts/advanced-state-management-with-react-and-codemirror/CodeEditor/index.ts
src/content/blog/drafts/advanced-state-management-with-react-and-codemirror/advanced-state-management-with-react-and-codemirror.mdx
src/styles/Mermaid.scss
yarn.lock

This PR:
- 📦 Add @codemirror/lang-sql 
- 🎨 Add circle, loading, error, and play icons
- 🛠️ Refactor Icon and remove unneeded features 
- ✨ Support disabled as prop on Button
- 🎨 Improve Mermaid styles on subgroups
- ✨ Add footer, ref, sql support to CodeEditor
- ✨ Add SQL terminal code editor for article
- 📝 Add "Advanced State Mangement" article
No

📝 Initial version of "Advanced State Management with React and Codemirror"

---

scripts/create-blog-post.js
src/pages/index.tsx

This PR:
- Fixes the greeting flash bug on the homepage, pinning the greeting to just `Hi, I'm Trevor`
- Fix number of years at Shopify
- Prettier chore
No

🐛 Fix greeting bug

---

src/content/blog/2024/loaves-and-fishes/loaves-and-fishes.mdx

This PR:
- Publish the "Loaves and Fishes" article
No

📝 Publish "Loaves and Fishes"

---

plugins/rehype-better-footnote-links/index.mjs
src/components/Button/Button.tsx
src/components/FeaturedTile/FeaturedTile.tsx
src/components/Icon/Icon.tsx
src/components/Icon/icons/arrow-right.svg
src/components/Icon/icons/arrow-undo.svg
src/components/ProjectTile/ProjectTile.tsx
src/pages/404.tsx
src/pages/index.tsx
src/styles/global.scss
src/templates/Post.tsx

This PR:
🎨 Replace ascii arrow with Atlas icon arrow
🎨 Replace ascii backlink arrow with Atlas icon
Resolves https://github.com/thetrevorharmon/thetrevorharmon.com/issues/227

🎨  Update ascii symbols with icons

---

src/components/FeaturedLinkTile/FeaturedLinkTile.tsx
src/components/FeaturedLinkTile/index.ts
src/components/index.tsx
src/content/blog/2024/const-isnt-constant/const-isnt-constant.md
src/pages/blog.tsx
src/pages/index.tsx

This PR:
📝 Add "Const isn't constant"
No

📝 Add "Const isn't constant"
